### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by bbybee1747** [bbybee1747/Pre-Work-Study-Guide#1]
## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that i can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript associated notes listed

**Comment by Joshua-Vankayalapati** [comment]
Hey bbybee1747,

I understand you want to create a static webpage to organize and display your prework notes on HTML, CSS, Git, and JavaScript.

Please note that while the webpage will show any data included in the source code, it won't save any new content or notes that you add directly on the page. For persistent data storage, you would need to use methods like Local Storage, Session Storage, or integrate with a backend server.

If you want me to create your static webpage. Assign me to this issue.
